### ISSUE TITLE
new version release

### ISSUE THREAD

**Issue by tarappo** [bitrise-io/ipa_analyzer#6]
I hope to release new version.
https://rubygems.org/gems/ipa_analyzer

**Comment by ghost** [comment]
Hi @tarappo! Unfortunately as we've migrated most of our tooling to Go, and continue that migration, I don't think it's very likely that this will be updated. 😦

**Comment by tarappo** [comment]
Oh..
 I made Pull Request and merged.
https://github.com/bitrise-io/ipa_analyzer/pull/5

But don't release, so I hope to release it.
